version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./DBproudpapers/data:/var/lib/mysql
      - ./DBproudpapers/init:/docker-entrypoint-initdb.d/:ro
      - ../../DBproudpapers/init.sql:/tmp/init.sql
    command: --init-file /tmp/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: abcABC123!!!
      MYSQL_DATABASE: proudpapers
      MYSQL_USER: proudpapers
      MYSQL_PASSWORD: abcABC123!!!
    ports:
    - "3309:3306"

  proudpapers:
    depends_on:
      - db
    image: proud-papers:latest
    build: ./app/
    ports:
    - "9000:8080"
    environment: 
        spring.datasource.url: jdbc:mysql://proudpapers_db_1/proudpapers
    restart: always