package ua.deti.tqs.easydeliversadmin.selenium;// Generated by Selenium IDE

import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.After;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.*;

@ExtendWith(SeleniumJupiter.class)
public class SucessfulloginTest {

  @Test
  public void sucessfullogin(FirefoxDriver driver) {
    driver.get("http://localhost:8080/login");
    driver.manage().window().setSize(new Dimension(550, 691));
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("jaguiar2@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("admin");
    driver.findElement(By.name("signup_submit")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".simple-text"));
      assert(elements.size() > 0);
    }
  }
}
