package ua.deti.tqs.easydeliversadmin.selenium;// Generated by Selenium IDE

import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.After;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

@ExtendWith(SeleniumJupiter.class)
public class UnsuccessfulLoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "/home/alexis/Downloads/geckodriver-v0.29.1-linux64/geckodriver");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After()
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void unsuccessfullogin() {
    driver.get("http://localhost:8080/login");
    driver.manage().window().setSize(new Dimension(783, 691));
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("wrongmail@ua.pt");
    driver.findElement(By.name("password")).sendKeys("wrongpass");
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("h1")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("h1"));
      assert(elements.size() > 0);
    }
  }
}
