version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./DBEasyDelivers/data:/var/lib/mysql
      - ./DBEasyDelivers/init:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: abcABC123!!!
      MYSQL_DATABASE: easydelivers
      MYSQL_USER: alexis
      MYSQL_PASSWORD: abcABC123!!!
    ports:
    - "3306:3306"

  easydelivers:
    depends_on:
      - db
    build: Platform/EasyDeliversAdmin
    ports:
    - "8080:8080"

