version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./DBEasyDelivers/data:/var/lib/mysql
      - ./DBEasyDelivers/init:/docker-entrypoint-initdb.d/:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abcABC123!!!
      MYSQL_DATABASE: easydelivers
      MYSQL_USER: alexis
      MYSQL_PASSWORD: abcABC123!!!

  wordpress:
    depends_on:
      - db
    build: Platform/EasyDeliversAdmin
    ports:
    - "8080:8080"
    restart: always

