name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: set up JDK 
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Test with Gradle
      run: cd EasyDelivers/RiderApp; ./gradlew test
      
    - name: Build with Gradle
      run: cd EasyDelivers/RiderApp; ./gradlew assemble
