
name: SonarCloud
on:
  push:
    branches:
      - main

  pull_request:
    branches: [ develop ]
    

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
 
      - name: Analyze with SonarCloud Platform
        run: cd EasyDelivers/Platform/EasyDeliversAdmin; ./mvnw -B verify sonar:sonar -Dsonar.projectKey=tqsproject_TQSFinalProject_EasyDelivers_Platform -Dsonar.organization=tqsproject -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.EASY_DELIVERS_PLATFORM }}

      - name: Grant execute permission for mvnw
        run: cd ProudPapers/app; chmod +x mvnw    

      - name: Analyze with SonarCloud ProudPapers
        run: cd ProudPapers/app; ./mvnw -B verify sonar:sonar -Dsonar.projectKey=tqsproject_TQSFinalProject_ProudPapers -Dsonar.organization=tqsproject -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.PROUD_PAPERS }}

      - name: Grant execute permission for gradlew
        run: cd EasyDelivers/RiderApp; chmod +x gradlew

      - name: Analyze with SonarCloud Riders App
        run: cd EasyDelivers/RiderApp; ./gradlew test jacocoTestReport sonarqube --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.RIDERAPP }}             
            

