
name: SonarCloud
on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Analyze with SonarCloud Platform
        run: cd EasyDelivers/Platform; mvnw -B verify sonar:sonar -Dsonar.projectKey=tqsproject_TQSFinalProject_EasyDelivers_Platform -Dsonar.organization=Wei93442 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Analyze with SonarCloud ProudPapers
        run: cd ProudPapers; mvnw -B verify sonar:sonar -Dsonar.projectKey=tqsproject_TQSFinalProject_ProudPapers -Dsonar.organization=Wei93442 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            
      - name: Grant execute permission for gradlew
        run: cd EasyDelivers/RiderApp; chmod +x gradlew

      - name: Analyze with SonarCloud Riders App
        run: cd EasyDelivers/RiderApp; ./gradlew verify  sonar:sonar -Dsonar.projectKey=tqsproject_TQSFinalProject_EasyDelivers_RiderApp -Dsonar.organization=Wei93442 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
