name: CD Easy Delivers
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run Easy Delivers Deployment
        run: |
          cd EasyDelivers/Platform/EasyDeliversAdmin
          docker-compose down
          docker-compose pull
          docker-compose up -d --build
  