name: CI for EasyDeliversAdmin
on:
  push:
    branches:
    - feature/adminaccess
  pull_request:
    branches:
    - develop 
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Go to the EasyDeliversAdmin project folder
        run: cd EasyDelivers/Platform/EasyDeliversAdmin
      - name: Give execution permissions
        run: chmod +x mvnw  
      - name: Clean and compile code
        run: ./mvnw clean install
      - name: Run tests
        run: ./mvnw test
