name: CI for ProudPapers with Sonarcloud
on:
  push:
    branches:
      - main

  pull_request:
    branches: [ develop ]

jobs:
  run_tests:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Grant execute permission for mvnw
        run: cd ProudPapers/app; chmod +x mvnw  
      - name: Build & Test & Analyze
        run: cd ProudPapers/app; ./mvnw -B clean verify sonar:sonar -Dsonar.projectKey=tqsproject_TQSFinalProject_ProudPapers -Dsonar.organization=tqsproject -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.PROUD_PAPERS }}